version: "3.0"

services:
  order-db:
    image: mongo:3.6.23-xenial
    volumes:
      - "/data/order-db"
    ports:
      - 27017:27017

  consumer-db:
    image: mongo:3.6.23-xenial
    volumes:
      - "/data/consumer-db"
    ports:
      - 3001:27017
    
  kitchen-db:
    image: mongo:3.6.23-xenial
    volumes:
      - "/data/kitchen-db"
    ports:
      - 3002:27017
    
  accounting-db:
    image: mongo:3.6.23-xenial
    volumes:
      - "/data/accounting-db"
    ports:
      - 3003:27017

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
       ZOOKEEPER_CLIENT_PORT: 2181
      
  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "9094:9094"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_LISTENERS: INTERNAL://:9092,OUTSIDE://:9094
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9092,OUTSIDE://localhost:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,OUTSIDE:PLAINTEXT
    extra_hosts:
      - "localhost:172.17.0.1"

  kafka-topics-generator:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - kafka
    command: >
      bash -c
      "sleep 5s &&
      kafka-topics --create --topic=order-created --if-not-exists --bootstrap-server=kafka:9092 && 
      kafka-topics --create --topic=order-approved --if-not-exists --bootstrap-server=kafka:9092 && 
      kafka-topics --create --topic=ticket-created-updated --if-not-exists --bootstrap-server=kafka:9092 &&
      kafka-topics --create --topic=consumer-verified --if-not-exists --bootstrap-server=kafka:9092 &&
      kafka-topics --create --topic=credit-card-authorized --if-not-exists --bootstrap-server=kafka:9092"
    extra_hosts:
      - "localhost:172.17.0.1"

  control-center:
    image: confluentinc/cp-enterprise-control-center:6.0.1
    hostname: control-center
    depends_on:
      - kafka
    ports:
      - "9021:9021"
    environment:
      CONTROL_CENTER_BOOTSTRAP_SERVERS: "kafka:9092"
      CONTROL_CENTER_REPLICATION_FACTOR: 1
      PORT: 9021

